apiVersion: v1
kind: Endpoints
metadata:
  name: api-portal-db-extip-{{ .Values.deployto.name }}
  namespace: api-portal
{{- if eq $.Values.deployto.name "prod" }}
{{ template "dbprod.yaml" . }}
{{- else if eq $.Values.deployto.name "int"}}
{{ template "dbint.yaml" . }}
{{- else if eq $.Values.deployto.name "qa"}}
{{ template "dbqa.yaml" . }}
{{- else if eq $.Values.deployto.name "dev"}}
{{ template "dbdev.yaml" . }}
{{- end }}
