apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-portal-pv-{{ .Values.deployto.name }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  nfs:
    path: /export/drupal
    {{- if eq $.Values.deployto.name "prod" }}
    server: {{ .Values.mountnfs.prod}}
    {{- else if eq $.Values.deployto.name "int"}}
    server: {{ .Values.mountnfs.int}}
    {{- else if eq $.Values.deployto.name "qa"}}
    server: {{ .Values.mountnfs.qa}}
    {{- else if eq $.Values.deployto.name "dev"}}
    server: {{ .Values.mountnfs.dev}}
    {{- end }}
