apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-portal-pv-claim-{{ .Values.deployto.name }}
  namespace: api-portal
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  resources:
    requests:
      storage: 5Gi
