apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.getsecret.data }}
kind: Secret
metadata:
  creationTimestamp: null
  name: drupalsecret
  namespace: api-portal
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/dockerconfigjson
