apiVersion: v1
kind: Service
metadata:
  name: api-load-balancer-{{ .Values.deployto.name }}
  namespace: api-portal
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  selector:
    app: api-portal-{{ .Values.deployto.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
